// ═══════════════════════════════════════════════════════════════════════════
// STORESGO SELLER SEO DATA — Auto-generated by deployment script
// DO NOT EDIT MANUALLY — Make changes in deployment script
// ═══════════════════════════════════════════════════════════════════════════

export interface Cuisine {
  slug: string;
  label: string;
  region: "caribbean" | "latin" | "african" | "asian" | "middle-eastern";
  flag: string;
  keywords: string[];
  diaspora: string;
  popularProducts?: string[];
}

export interface Location {
  slug: string;
  label: string;
  state: string;
  type: "region" | "county" | "city";
  county?: string;
}

export interface Solution {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  problem: string;
  problemDetail: string[];
  solution: string;
  solutionPoints: string[];
  keywords: string[];
  icon: string;
}

export interface Competitor {
  slug: string;
  name: string;
  metaTitle: string;
  metaDescription: string;
  description: string;
  focus: string;
  commission: string;
  storesgoAdvantages: string[];
  competitorAdvantages: string[];
  chooseThem: string[];
  chooseUs: string[];
  keywords: string[];
}

export interface Guide {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  sections: Array<{ heading: string; content: string }>;
  keywords: string[];
  cta: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// CUISINES (52 total)
// ═══════════════════════════════════════════════════════════════════════════

export const CUISINES: Cuisine[] = [
  // Caribbean (12)
  { slug: "caribbean", label: "Caribbean", region: "caribbean", flag: "🌴", keywords: ["jerk", "ackee", "plantain", "patty", "oxtail"], diaspora: "Caribbean", popularProducts: ["Jerk seasoning", "Ackee", "Scotch bonnet peppers", "Plantains"] },
  { slug: "jamaican", label: "Jamaican", region: "caribbean", flag: "🇯🇲", keywords: ["jerk seasoning", "ackee", "jamaican patty"], diaspora: "Jamaican", popularProducts: ["Grace coconut milk", "Walkerswood jerk", "Jamaican patties"] },
  { slug: "haitian", label: "Haitian", region: "caribbean", flag: "🇭🇹", keywords: ["griot", "pikliz", "epis"], diaspora: "Haitian", popularProducts: ["Djon djon mushrooms", "Epis seasoning", "Piklis"] },
  { slug: "cuban", label: "Cuban", region: "caribbean", flag: "🇨🇺", keywords: ["mojo", "yuca", "cuban coffee"], diaspora: "Cuban", popularProducts: ["Cuban coffee", "Mojo criollo", "Guava paste"] },
  { slug: "trinidadian", label: "Trinidadian", region: "caribbean", flag: "🇹🇹", keywords: ["doubles", "roti", "pepper sauce"], diaspora: "Trinidadian", popularProducts: ["Doubles", "Trinidad pepper sauce", "Curry powder"] },
  { slug: "puerto-rican", label: "Puerto Rican", region: "caribbean", flag: "🇵🇷", keywords: ["sofrito", "mofongo", "adobo", "sazon"], diaspora: "Puerto Rican", popularProducts: ["Goya sofrito", "Sazon", "Adobo"] },
  { slug: "dominican", label: "Dominican", region: "caribbean", flag: "🇩🇴", keywords: ["mangu", "sancocho"], diaspora: "Dominican", popularProducts: ["Dominican salami", "Mamajuana", "Platanos"] },
  { slug: "guyanese", label: "Guyanese", region: "caribbean", flag: "🇬🇾", keywords: ["pepperpot", "roti", "cassareep"], diaspora: "Guyanese", popularProducts: ["Cassareep", "Guyanese pepper sauce"] },
  { slug: "bahamian", label: "Bahamian", region: "caribbean", flag: "🇧🇸", keywords: ["conch", "johnnycake"], diaspora: "Bahamian", popularProducts: ["Conch salad", "Kalik beer"] },
  { slug: "barbadian", label: "Barbadian", region: "caribbean", flag: "🇧🇧", keywords: ["cou cou", "flying fish", "bajan seasoning"], diaspora: "Barbadian/Bajan", popularProducts: ["Bajan pepper sauce", "Banks beer"] },
  { slug: "vincentian", label: "Vincentian", region: "caribbean", flag: "🇻🇨", keywords: ["breadfruit", "callaloo"], diaspora: "Vincentian", popularProducts: ["Hairoun beer", "Breadfruit"] },
  { slug: "grenadian", label: "Grenadian", region: "caribbean", flag: "🇬🇩", keywords: ["oil down", "nutmeg", "cocoa"], diaspora: "Grenadian", popularProducts: ["Grenadian nutmeg", "Cocoa balls"] },

  // Latin (12)
  { slug: "hispanic", label: "Hispanic/Latin", region: "latin", flag: "🌎", keywords: ["tortilla", "salsa", "beans", "rice"], diaspora: "Hispanic/Latino", popularProducts: ["Goya products", "La Costena", "Badia spices"] },
  { slug: "mexican", label: "Mexican", region: "latin", flag: "🇲🇽", keywords: ["tortilla", "salsa", "masa", "chile", "mole"], diaspora: "Mexican", popularProducts: ["Maseca", "La Costena", "Valentina", "Tajin"] },
  { slug: "colombian", label: "Colombian", region: "latin", flag: "🇨🇴", keywords: ["arepa", "pandebono", "empanada"], diaspora: "Colombian", popularProducts: ["Arepas", "Pandebono", "Colombian coffee"] },
  { slug: "venezuelan", label: "Venezuelan", region: "latin", flag: "🇻🇪", keywords: ["arepa", "cachapa", "tequeños"], diaspora: "Venezuelan", popularProducts: ["Harina PAN", "Tequeños", "Cachapas"] },
  { slug: "peruvian", label: "Peruvian", region: "latin", flag: "🇵🇪", keywords: ["aji", "quinoa", "ceviche"], diaspora: "Peruvian", popularProducts: ["Aji amarillo", "Quinoa", "Inca Kola"] },
  { slug: "salvadoran", label: "Salvadoran", region: "latin", flag: "🇸🇻", keywords: ["pupusa", "curtido"], diaspora: "Salvadoran", popularProducts: ["Pupusa mix", "Curtido", "Loroco"] },
  { slug: "guatemalan", label: "Guatemalan", region: "latin", flag: "🇬🇹", keywords: ["tamales", "pepian"], diaspora: "Guatemalan", popularProducts: ["Guatemalan coffee", "Black beans"] },
  { slug: "honduran", label: "Honduran", region: "latin", flag: "🇭🇳", keywords: ["baleada", "sopa de caracol"], diaspora: "Honduran", popularProducts: ["Baleada ingredients", "Honduran coffee"] },
  { slug: "nicaraguan", label: "Nicaraguan", region: "latin", flag: "🇳🇮", keywords: ["gallo pinto", "nacatamal"], diaspora: "Nicaraguan", popularProducts: ["Pinolillo", "Tona beer"] },
  { slug: "brazilian", label: "Brazilian", region: "latin", flag: "🇧🇷", keywords: ["feijoada", "pao de queijo", "acai"], diaspora: "Brazilian", popularProducts: ["Guarana Antarctica", "Pao de queijo", "Acai"] },
  { slug: "argentinian", label: "Argentinian", region: "latin", flag: "🇦🇷", keywords: ["empanada", "chimichurri", "dulce de leche"], diaspora: "Argentinian", popularProducts: ["Yerba mate", "Dulce de leche", "Alfajores"] },
  { slug: "ecuadorian", label: "Ecuadorian", region: "latin", flag: "🇪🇨", keywords: ["encebollado", "llapingachos"], diaspora: "Ecuadorian", popularProducts: ["Pilsener beer", "Ecuadorian chocolate"] },

  // African (10)
  { slug: "african", label: "African", region: "african", flag: "🌍", keywords: ["fufu", "jollof", "palm oil", "egusi"], diaspora: "African", popularProducts: ["Palm oil", "Egusi seeds", "Fufu flour"] },
  { slug: "nigerian", label: "Nigerian", region: "african", flag: "🇳🇬", keywords: ["jollof rice", "egusi", "fufu", "suya"], diaspora: "Nigerian", popularProducts: ["Egusi", "Palm oil", "Stockfish", "Garri"] },
  { slug: "ghanaian", label: "Ghanaian", region: "african", flag: "🇬🇭", keywords: ["banku", "kenkey", "waakye"], diaspora: "Ghanaian", popularProducts: ["Shito", "Kenkey", "Banku mix"] },
  { slug: "ethiopian", label: "Ethiopian", region: "african", flag: "🇪🇹", keywords: ["injera", "berbere", "doro wat"], diaspora: "Ethiopian", popularProducts: ["Teff flour", "Berbere spice", "Ethiopian coffee"] },
  { slug: "senegalese", label: "Senegalese", region: "african", flag: "🇸🇳", keywords: ["thieboudienne", "yassa", "mafe"], diaspora: "Senegalese", popularProducts: ["Bissap", "Tamarind", "Mafe sauce"] },
  { slug: "cameroonian", label: "Cameroonian", region: "african", flag: "🇨🇲", keywords: ["ndole", "eru", "fufu corn"], diaspora: "Cameroonian", popularProducts: ["Eru leaves", "Ndole", "White pepper"] },
  { slug: "kenyan", label: "Kenyan", region: "african", flag: "🇰🇪", keywords: ["ugali", "sukuma wiki", "nyama choma"], diaspora: "Kenyan", popularProducts: ["Kenyan tea", "Ugali flour", "Tusker beer"] },
  { slug: "somali", label: "Somali", region: "african", flag: "🇸🇴", keywords: ["sambusa", "canjeero", "suqaar"], diaspora: "Somali", popularProducts: ["Xawaash spice", "Somali tea", "Halwa"] },
  { slug: "south-african", label: "South African", region: "african", flag: "🇿🇦", keywords: ["biltong", "boerewors", "chakalaka"], diaspora: "South African", popularProducts: ["Biltong", "Boerewors", "Rooibos tea"] },
  { slug: "congolese", label: "Congolese", region: "african", flag: "🇨🇩", keywords: ["fufu", "pondu", "saka saka"], diaspora: "Congolese", popularProducts: ["Pondu", "Saka saka", "Palm oil"] },

  // Asian (12)
  { slug: "asian", label: "Asian", region: "asian", flag: "🥢", keywords: ["rice", "noodles", "soy sauce", "tofu"], diaspora: "Asian", popularProducts: ["Jasmine rice", "Soy sauce", "Rice noodles"] },
  { slug: "indian", label: "Indian", region: "asian", flag: "🇮🇳", keywords: ["curry", "dal", "basmati", "masala", "ghee"], diaspora: "Indian", popularProducts: ["Basmati rice", "Ghee", "Masala spices", "Paneer"] },
  { slug: "pakistani", label: "Pakistani", region: "asian", flag: "🇵🇰", keywords: ["biryani", "nihari", "haleem"], diaspora: "Pakistani", popularProducts: ["Shan masala", "Basmati rice", "Rooh Afza"] },
  { slug: "bangladeshi", label: "Bangladeshi", region: "asian", flag: "🇧🇩", keywords: ["hilsa", "pitha", "bhuna"], diaspora: "Bangladeshi", popularProducts: ["Hilsa fish", "Pitha mix", "Mustard oil"] },
  { slug: "filipino", label: "Filipino", region: "asian", flag: "🇵🇭", keywords: ["adobo", "pancit", "lumpia", "ube"], diaspora: "Filipino", popularProducts: ["Ube jam", "Lumpia wrappers", "Sinigang mix"] },
  { slug: "vietnamese", label: "Vietnamese", region: "asian", flag: "🇻🇳", keywords: ["pho", "banh mi", "fish sauce"], diaspora: "Vietnamese", popularProducts: ["Pho spices", "Fish sauce", "Rice paper"] },
  { slug: "chinese", label: "Chinese", region: "asian", flag: "🇨🇳", keywords: ["soy sauce", "dim sum", "noodles"], diaspora: "Chinese", popularProducts: ["Lee Kum Kee sauces", "Jasmine rice", "Dumpling wrappers"] },
  { slug: "korean", label: "Korean", region: "asian", flag: "🇰🇷", keywords: ["kimchi", "gochujang", "bulgogi"], diaspora: "Korean", popularProducts: ["Kimchi", "Gochujang", "Korean ramyun", "Soju"] },
  { slug: "japanese", label: "Japanese", region: "asian", flag: "🇯🇵", keywords: ["miso", "dashi", "nori", "sake"], diaspora: "Japanese", popularProducts: ["Miso paste", "Nori seaweed", "Sake", "Panko"] },
  { slug: "thai", label: "Thai", region: "asian", flag: "🇹🇭", keywords: ["curry paste", "fish sauce", "coconut milk"], diaspora: "Thai", popularProducts: ["Thai curry paste", "Coconut milk", "Fish sauce"] },
  { slug: "indonesian", label: "Indonesian", region: "asian", flag: "🇮🇩", keywords: ["sambal", "rendang", "tempeh"], diaspora: "Indonesian", popularProducts: ["Sambal", "Kecap manis", "Indomie"] },
  { slug: "malaysian", label: "Malaysian", region: "asian", flag: "🇲🇾", keywords: ["rendang", "nasi lemak", "satay"], diaspora: "Malaysian", popularProducts: ["Laksa paste", "Satay sauce", "Belacan"] },

  // Middle Eastern (6)
  { slug: "middle-eastern", label: "Middle Eastern", region: "middle-eastern", flag: "🧆", keywords: ["hummus", "tahini", "falafel", "pita"], diaspora: "Middle Eastern", popularProducts: ["Hummus", "Tahini", "Pita bread", "Za'atar"] },
  { slug: "lebanese", label: "Lebanese", region: "middle-eastern", flag: "🇱🇧", keywords: ["hummus", "tabbouleh", "kibbeh"], diaspora: "Lebanese", popularProducts: ["Hummus", "Tabbouleh", "Lebanese coffee"] },
  { slug: "persian", label: "Persian/Iranian", region: "middle-eastern", flag: "🇮🇷", keywords: ["saffron", "tahdig", "ghormeh sabzi"], diaspora: "Persian/Iranian", popularProducts: ["Saffron", "Zereshk berries", "Persian rice"] },
  { slug: "turkish", label: "Turkish", region: "middle-eastern", flag: "🇹🇷", keywords: ["baklava", "kebab", "borek"], diaspora: "Turkish", popularProducts: ["Turkish delight", "Baklava", "Turkish coffee"] },
  { slug: "moroccan", label: "Moroccan", region: "middle-eastern", flag: "🇲🇦", keywords: ["couscous", "tagine", "harissa"], diaspora: "Moroccan", popularProducts: ["Couscous", "Harissa", "Preserved lemons"] },
  { slug: "egyptian", label: "Egyptian", region: "middle-eastern", flag: "🇪🇬", keywords: ["koshari", "ful medames", "molokhia"], diaspora: "Egyptian", popularProducts: ["Ful medames", "Molokhia", "Dukkah"] },
];

// ═══════════════════════════════════════════════════════════════════════════
// LOCATIONS (South Florida - Phase 1)
// ═══════════════════════════════════════════════════════════════════════════

export const LOCATIONS: Location[] = [
  { slug: "south-florida", label: "South Florida", state: "FL", type: "region" },
  { slug: "miami-dade", label: "Miami-Dade County", state: "FL", type: "county" },
  { slug: "broward", label: "Broward County", state: "FL", type: "county" },
  { slug: "palm-beach", label: "Palm Beach County", state: "FL", type: "county" },
];

// ═══════════════════════════════════════════════════════════════════════════
// SOLUTIONS
// ═══════════════════════════════════════════════════════════════════════════

export const SOLUTIONS: Solution[] = [
  {
    slug: "local-delivery",
    title: "Local Grocery Delivery Solution",
    metaTitle: "Local Grocery Delivery for Ethnic Stores | StoresGo",
    metaDescription: "Reduce delivery costs with StoresGo's local fulfillment. Same-day delivery for ethnic grocery stores in South Florida.",
    problem: "High shipping costs eating into your margins?",
    problemDetail: ["National shipping is expensive ($8-15 per order)", "Perishable items often arrive damaged", "Customers expect Amazon-like delivery speeds", "Managing your own delivery is a full-time job"],
    solution: "StoresGo handles local delivery so you don't have to.",
    solutionPoints: ["Same-day delivery in South Florida", "We pick up from your store and deliver", "Flat-rate pricing — no surprises", "Perfect for perishables and fresh produce", "Track every order in real-time"],
    keywords: ["reduce grocery delivery costs", "local delivery management for grocers", "optimize last mile delivery"],
    icon: "🚚",
  },
  {
    slug: "reach-diaspora-customers",
    title: "Reach Diaspora Customers Online",
    metaTitle: "Reach Caribbean & Ethnic Diaspora Customers | StoresGo",
    metaDescription: "Your customers moved but still crave your products. StoresGo helps ethnic grocery stores reach diaspora communities across South Florida.",
    problem: "Your customers moved away but still want your products?",
    problemDetail: ["Caribbean/Latin/African diaspora is spread across South Florida", "They can't drive 30 minutes to your store anymore", "National shipping is too expensive for regular orders"],
    solution: "StoresGo delivers your products to diaspora customers across South Florida.",
    solutionPoints: ["Reach customers in all 3 South Florida counties", "They order online, we deliver from your store", "Build a loyal customer base beyond your neighborhood", "Multi-language support (Creole, Spanish)"],
    keywords: ["how to reach caribbean diaspora customers", "ethnic food marketing strategy", "sell to diaspora community online"],
    icon: "🌍",
  },
  {
    slug: "compete-big-players",
    title: "Compete with Amazon & Walmart Grocery",
    metaTitle: "How Small Grocers Compete with Amazon | StoresGo",
    metaDescription: "Don't lose customers to Amazon Fresh. StoresGo helps independent ethnic grocery stores compete with local, same-day delivery.",
    problem: "Losing customers to Amazon Fresh and Walmart?",
    problemDetail: ["Big players offer fast, cheap delivery", "They're adding more ethnic products every month", "Customers value convenience over loyalty"],
    solution: "Beat them at the local game with StoresGo.",
    solutionPoints: ["Same-day delivery — faster than Amazon", "Authentic products they can't source", "Local, community-focused experience", "Personal service big players can't match"],
    keywords: ["compete with amazon fresh walmart grocery", "independent grocer e-commerce strategy", "local grocery vs amazon"],
    icon: "🏆",
  },
  {
    slug: "get-online-fast",
    title: "Get Your Grocery Store Online Fast",
    metaTitle: "Get Your Grocery Store Online in Days | StoresGo",
    metaDescription: "Launch your online store in days, not months. StoresGo handles setup, delivery, and payments. You just add products.",
    problem: "Need to start selling online but don't know where to start?",
    problemDetail: ["Building a website is expensive and slow", "Learning e-commerce takes time you don't have", "Setting up delivery is complicated"],
    solution: "StoresGo gets you online in days — not months.",
    solutionPoints: ["Sign up in 2 minutes", "We create your store page for you", "Add products with photos from your phone", "We handle delivery and payments", "Be selling online within a week"],
    keywords: ["how to get my grocery store online fast", "grocery store vendor application", "quick grocery e-commerce setup"],
    icon: "⚡",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// COMPETITORS
// ═══════════════════════════════════════════════════════════════════════════

export const COMPETITORS: Competitor[] = [
  {
    slug: "caribshopper",
    name: "Caribshopper",
    metaTitle: "StoresGo vs Caribshopper: Which Is Better for Caribbean Stores?",
    metaDescription: "Compare StoresGo vs Caribshopper for selling Caribbean food online. Local delivery vs national shipping, commissions, features.",
    description: "Caribbean food marketplace serving US and Canada",
    focus: "National Caribbean food shipping",
    commission: "~20%",
    storesgoAdvantages: ["Local same-day delivery (not slow shipping)", "Lower commission (15% vs 20%)", "South Florida focused = faster delivery", "Multi-ethnic (Caribbean + Latin + African + Asian)", "Fresh produce and perishables friendly"],
    competitorAdvantages: ["National reach across US/Canada", "Established Caribbean brand", "Wholesale/B2B program"],
    chooseThem: ["You want to ship nationally", "You only sell shelf-stable products", "You're focused on B2B wholesale"],
    chooseUs: ["You're in South Florida", "You want same-day local delivery", "You sell fresh/perishable products", "You want lower commission rates"],
    keywords: ["caribshopper alternative", "caribshopper vs storesgo", "caribshopper competitor"],
  },
  {
    slug: "shopify",
    name: "Shopify",
    metaTitle: "StoresGo vs Shopify for Grocery Stores: Full Comparison",
    metaDescription: "Should you use Shopify or StoresGo for your grocery store? Compare features, costs, and delivery options.",
    description: "DIY e-commerce platform",
    focus: "Build your own website",
    commission: "$29-299/mo + transaction fees",
    storesgoAdvantages: ["We handle delivery — Shopify doesn't", "No monthly fees — pay only when you sell", "No technical setup required", "Built-in local delivery network"],
    competitorAdvantages: ["Full control over your brand", "Own your customer data", "Unlimited customization"],
    chooseThem: ["You want 100% brand control", "You have budget for monthly fees", "You'll handle your own delivery"],
    chooseUs: ["You want to start selling fast", "You don't want to manage delivery", "You prefer zero monthly fees"],
    keywords: ["shopify for grocery store", "shopify vs grocery marketplace", "storesgo vs shopify for grocery"],
  },
  {
    slug: "instacart",
    name: "Instacart",
    metaTitle: "StoresGo vs Instacart for Small Grocery Stores",
    metaDescription: "Compare StoresGo vs Instacart for ethnic grocery stores. Own your customers, keep more revenue.",
    description: "Grocery delivery platform",
    focus: "Mass-market grocery delivery",
    commission: "15-30% + fees",
    storesgoAdvantages: ["You own the customer relationship", "Lower, transparent commission (15%)", "Ethnic grocery focused", "Your brand, not Instacart's"],
    competitorAdvantages: ["Massive existing customer base", "Household name recognition", "Shopper network already built"],
    chooseThem: ["You want access to their huge customer base", "You're okay with them owning the customer"],
    chooseUs: ["You want to own your customer relationships", "You're an ethnic/specialty grocery store", "You prefer transparent, lower fees"],
    keywords: ["instacart for sellers", "instacart alternative for small grocery", "instacart commission vs storesgo"],
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// GUIDES
// ═══════════════════════════════════════════════════════════════════════════

export const GUIDES: Guide[] = [
  {
    slug: "start-ethnic-food-business-online",
    title: "How to Start an Online Ethnic Food Business (2025 Guide)",
    metaTitle: "Start an Online Ethnic Food Business in 2025 | Complete Guide",
    metaDescription: "Learn how to start selling ethnic food online. Permits, platforms, marketing, and logistics.",
    intro: "The ethnic food market is booming. Here's how to get your slice of this growing industry.",
    sections: [
      { heading: "Why Sell Ethnic Food Online in 2025?", content: "The ethnic food market is projected to reach $50 billion by 2026. Diaspora communities are hungry for authentic products." },
      { heading: "Step 1: Understand Your Market", content: "Identify your target diaspora community. Caribbean, Latin, African, and Asian communities all have distinct preferences." },
      { heading: "Step 2: Handle Permits and Regulations", content: "You'll need a business license, food handler's permit, and potentially FDA registration for certain products." },
      { heading: "Step 3: Choose Your Platform", content: "Options include building your own website (Shopify), joining a marketplace (StoresGo), or both." },
    ],
    keywords: ["starting an online ethnic food business", "online food permits and regulations", "how to start selling ethnic food online"],
    cta: "Ready to start? Join StoresGo and be selling online within a week.",
  },
  {
    slug: "ethnic-grocery-market-trends-2025",
    title: "Ethnic Grocery Market Trends & Statistics 2025",
    metaTitle: "Ethnic Grocery Market Trends 2025 | Industry Statistics",
    metaDescription: "Discover 2025 ethnic grocery market trends. Statistics on Caribbean, Latin, African, and Asian food sales.",
    intro: "The ethnic grocery market is one of the fastest-growing segments in food retail.",
    sections: [
      { heading: "Market Size & Growth", content: "The US ethnic food market is valued at over $40 billion and growing at 10%+ annually." },
      { heading: "Diaspora Demographics", content: "South Florida alone has 850,000+ Caribbean-born residents, 4+ million Hispanic residents." },
      { heading: "Online Grocery Trends", content: "Online grocery sales have doubled since 2020. Ethnic grocery e-commerce is growing even faster." },
    ],
    keywords: ["ethnic grocery market 2025", "ethnic food e-commerce trends", "online grocery shopping statistics"],
    cta: "Position your store to capture this growing market. Join StoresGo today.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════

export function getCuisineBySlug(slug: string): Cuisine | undefined {
  return CUISINES.find(c => c.slug === slug);
}

export function getLocationBySlug(slug: string): Location | undefined {
  return LOCATIONS.find(l => l.slug === slug);
}

export function getSolutionBySlug(slug: string): Solution | undefined {
  return SOLUTIONS.find(s => s.slug === slug);
}

export function getCompetitorBySlug(slug: string): Competitor | undefined {
  return COMPETITORS.find(c => c.slug === slug);
}

export function getGuideBySlug(slug: string): Guide | undefined {
  return GUIDES.find(g => g.slug === slug);
}

export function getCuisinesByRegion(region: string): Cuisine[] {
  return CUISINES.filter(c => c.region === region);
}

export function getRelatedCuisines(cuisineSlug: string, limit = 4): Cuisine[] {
  const cuisine = getCuisineBySlug(cuisineSlug);
  if (!cuisine) return CUISINES.slice(0, limit);
  const sameRegion = CUISINES.filter(c => c.region === cuisine.region && c.slug !== cuisineSlug);
  const otherRegion = CUISINES.filter(c => c.region !== cuisine.region);
  return [...sameRegion, ...otherRegion].slice(0, limit);
}

export function getNearbyLocations(locationSlug: string, limit = 3): Location[] {
  return LOCATIONS.filter(l => l.slug !== locationSlug).slice(0, limit);
}

export function getAllSellerPageCombinations(): Array<{ cuisine: string; location: string }> {
  const combinations: Array<{ cuisine: string; location: string }> = [];
  for (const cuisine of CUISINES) {
    for (const location of LOCATIONS) {
      combinations.push({ cuisine: cuisine.slug, location: location.slug });
    }
  }
  return combinations;
}
